<?php
/**
 * Created by PhpStorm.
 * User: HAIHS
 * Date: 11/6/2017
 * Time: 10:38 PM
 */

namespace frontend\widgets;


use cms\models\TbLanguage;
use yii\base\Widget;

class LeftMenu extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $key   = 'keyword-cache-hot';
        $cache = \Yii::$app->cache;
        if (($keywords = $cache->get($key)) === false) {
            $keywords = TbLanguage::find()->select(['name','link'])->where(['is_hot'=>1])->all();
            $cache->set($key, $keywords, \Yii::$app->params['CACHE_TIME']['HOUR']);
        }

        return $this->render('_left_menu',[
            'keywords' =>$keywords
        ]);
    }
}