<?php
    /**
     * Created by PhpStorm.
     * User: HAIHS
     * Date: 11/6/2017
     * Time: 11:27 PM
     */

    namespace frontend\widgets;


    use cms\models\TbNews;
    use yii\base\Widget;

    class NewsHot extends Widget
    {

        const LIMIT = 4;
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
        }

        public function run()
        {
            parent::run(); // TODO: Change the autogenerated stub

            $articleHot = \cms\models\TbNews::getArticleHot(self::LIMIT);

            return $this->render('_newsHot',[
                'data' => $articleHot
            ]);
        }
    }